_wandb:
    value:
        cli_version: 0.22.1
        e:
            d04a0ocedq59s685pnfu3e7n9gnb6t0q:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "424194076672"
                        used: "264235556864"
                email: li1872156233@outlook.com
                executable: E:\Software\Python_env\Anaconda3\envs\hf_LLM_env\python.exe
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-32653202-3ebd-47a1-0f37-25b948c20aa4
                host: DESKTOP-FN92J53
                memory:
                    total: "33599344640"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\Ruizhe\Desktop\Study\Code\AI\transformer\model\train.py
                python: CPython 3.9.21
                root: C:\Users\Ruizhe\Desktop\Study\Code\AI\transformer\model
                startedAt: "2025-10-04T23:17:35.974069Z"
                writerId: d04a0ocedq59s685pnfu3e7n9gnb6t0q
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.9.21
            "5": 0.22.1
            "8":
                - 3
            "12": 0.22.1
            "13": windows-amd64
batch_size:
    value: 32
context_lengh:
    value: 10000000
d_ff:
    value: 3072
d_model:
    value: 768
data_path:
    value: C:\Users\Ruizhe\Desktop\Study\ID2221\Project\Data\pubmedqa\ori_pqau.json
device:
    value: cuda
dropout:
    value: 0.1
learning_rate:
    value: 0.0001
max_len:
    value: 100
num_epochs:
    value: 5
num_heads:
    value: 8
num_layers:
    value: 6
pad_idx:
    value: null
save_path:
    value: best_model.pt
use_wandb:
    value: true
vocab_path:
    value: ../tokenizer/vocab_test_set.npy
vocab_size:
    value: null
wandb_project:
    value: pubmedqa-training
wandb_run_name:
    value: run-20251005-011735
